services:

  bugtracker:
    build:
      context: .
      dockerfile: Dockerfile-multi
    container_name: bugtracker
    volumes:
      - staticfiles_volume:/app/staticfiles
    networks:
      - bugtracker-network
    
  reverse_proxy:
    image: "nginx:1.25-alpine"
    ports:
      - 80:80
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles_volume:/app/staticfiles
    depends_on: 
      - bugtracker
    networks:
      - bugtracker-network
    restart: always

networks:
  bugtracker-network:

volumes:
  staticfiles_volume: